# **Simple Neural Network**

![nn2](../assets/nn_2.jpg)

In [1]:
import torch
from torch import nn

In [43]:
input_feature = torch.tensor([2,3], dtype=torch.float32)
input_feature

tensor([2., 3.])

In [63]:
torch.manual_seed(5)

linear_1 = nn.Linear(2,3, bias=True)
print("Pesos Layer 1\n\n",linear_1.weight)
print("Bias Layer 1\n\n",linear_1.bias)

linear_2 = nn.Linear(3,2, bias=True)
print("\nPesos Layer 2\n\n",linear_2.weight)
print("Bias Layer 2\n\n",linear_2.bias)

out = nn.Linear(2, 1, bias=True)
print("\nPesos Out Layer\n\n",out.weight)
print("Bias Out Layer\n\n",out.bias)

Pesos Layer 1

 Parameter containing:
tensor([[ 0.4670, -0.5288],
        [ 0.5762,  0.4524],
        [ 0.5941, -0.5421]], requires_grad=True)
Bias Layer 1

 Parameter containing:
tensor([-0.4746,  0.3365, -0.6601], requires_grad=True)

Pesos Layer 2

 Parameter containing:
tensor([[ 0.5706,  0.1229,  0.0746],
        [-0.4937,  0.1840,  0.2483]], requires_grad=True)
Bias Layer 2

 Parameter containing:
tensor([0.0916, 0.5553], requires_grad=True)

Pesos Out Layer

 Parameter containing:
tensor([[ 0.2124, -0.6270]], requires_grad=True)
Bias Out Layer

 Parameter containing:
tensor([0.5941], requires_grad=True)


In [40]:
linear_1.bias

Parameter containing:
tensor([-0.4746,  0.3365, -0.6601], requires_grad=True)

In [ ]:
# z11 = W
z11 = linear_1.weight @ input_feature + linear_1.bias
z11

tensor([-1.1268,  2.8463, -1.0983], grad_fn=<AddBackward0>)

In [ ]:
# Ahora pasamos por la relu
z11 = torch.relu(z11)
z11

tensor([0.0000, 2.8463, 0.0000], grad_fn=<ReluBackward0>)

In [ ]:
# Otra forma de obtener la salida de la capa 1 más rápido
z11_2 = torch.relu(linear_1(input_feature))
z11_2

tensor([0.0000, 2.8463, 0.0000], grad_fn=<ReluBackward0>)

In [61]:
z_capa_2 = torch.relu(linear_2.weight @ z11 + linear_2.bias)
z_capa_2

tensor([0.4414, 1.0790], grad_fn=<ReluBackward0>)

In [64]:
y_out = out.weight @ z_capa_2 + out.bias 
y_out

tensor([0.0113], grad_fn=<AddBackward0>)

In [66]:
0.2124*0.4414-0.6270*1.0790+0.5941

0.01132036000000003