# **Standard Notation and PyTorch**

El siguiente notebook contiene la notación para trabajar con redes neuronales. Se mostrará todo el proceso que ocurre en una red neuronal simple, partiendo de realizar el proceso de manera manual y luego utilizando pytorch.

# **1. Standard Notation**

Vamos a suponer la siguiente red neuronal:

![nn](../assets/nn_1.jpg)

# **2. Breve Repaso de Álgebra**

In [25]:
import torch

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7,8],[9,10],[11,12]])

print("Dimensión de A:", a.shape)
print("Dimensión de B:", b.shape)

Dimensión de A: torch.Size([2, 3])
Dimensión de B: torch.Size([3, 2])


Para realizar la multiplicación matricial, el número de columnas de A debe coincidir con el de B, resultando una matriz C de tamaño (fila de A, columna de B).

In [27]:
# Realizo la operación de multiplicar matricialmente
c = a @ b
c

tensor([[ 58,  64],
        [139, 154]])

In [31]:
# Otras formas de realizar la misma operación

c_2 = torch.mm(a, b)
c_3 = torch.matmul(a, b)

In [32]:
c_2

tensor([[ 58,  64],
        [139, 154]])

In [33]:
c_3

tensor([[ 58,  64],
        [139, 154]])

# **3. Simple Neural Network (almost from scratch!)**

Ahora realizaremos el proceso de **forward** y **backward** manual, luego como se realiza tradicionalmente con pytorch.

## **3.1 Step-by-Step Forward and Backward**

### **3.1.1 Forward**

Vamos a suponer que tenemor una red con dos capas ocultas, de entrada tenemos dos feature y a la salida una neurona.

In [1]:
import torch 
from torch import nn

Creamos nuestras dos capas **Lineal 1** y **Lineal 2**, la primera tiene 3 neurona y la segunda tiene 3 neuronas.

In [19]:
torch.manual_seed(5)
lineal_1 = nn.Linear(2,3, bias=False)
lineal_2 = nn.Linear(3,1, bias=False)

Visualizamos los pesos generados aleatoriamente en cada capa lineal.

In [11]:
lineal_1.weight

Parameter containing:
tensor([[ 0.4670, -0.5288],
        [ 0.5762,  0.4524],
        [ 0.5941, -0.5421]], requires_grad=True)

In [20]:
lineal_2.weight

Parameter containing:
tensor([[-0.3875,  0.2747, -0.5389]], requires_grad=True)

Ahora vamos a realizar la operación de multiplicar matricialmente, de dos formas distintas.

In [38]:
x = torch.arange(1,3, dtype=torch.float32)
x

tensor([1., 2.])

#### **Método 1**

In [39]:
z1 = lineal_1(x)
z1

tensor([-0.5905,  1.4811, -0.4902], grad_fn=<SqueezeBackward4>)

Ahora el tensor obtenido, de 3 feature debe pasar por una función de activación.

In [42]:
z = nn.functional.relu(z1)
z

tensor([0.0000, 1.4811, 0.0000], grad_fn=<ReluBackward0>)

In [43]:
z2 = lineal_2(z)
z2

tensor([0.4069], grad_fn=<SqueezeBackward4>)

In [44]:
z = nn.functional.relu(z2)
z

tensor([0.4069], grad_fn=<ReluBackward0>)

#### **Método 2**

El método dos es realizando uno mismo las operaciones matriciales.

In [60]:
def mi_relu(x):

    lista = []
    
    for i in z1:
        if i >= 0:
            lista.append(float(i))
        else:
            lista.append(0)

    return torch.tensor(lista, dtype=torch.float32)

In [61]:
yy = mi_relu(z1)

In [62]:
yy

tensor([0.0000, 1.4811, 0.0000])

In [40]:
z1 = x @ lineal_1.weight.T

In [41]:
z1

tensor([-0.5905,  1.4811, -0.4902], grad_fn=<SqueezeBackward4>)