# **Standard Notation and PyTorch**

El siguiente notebook contiene la notación para trabajar con redes neuronales. Se mostrará todo el proceso que ocurre en una red neuronal simple, partiendo de realizar el proceso de manera manual y luego utilizando pytorch.

# **1. Standard Notation**

Vamos a suponer la siguiente red neuronal:

![nn](../assets/nn_1.jpg)

# **Pytorch**

In [1]:
import torch 
from torch import nn

In [19]:
torch.manual_seed(5)
lineal_1 = nn.Linear(2,3, bias=False)
lineal_2 = nn.Linear(3,1, bias=False)

In [11]:
lineal_1.weight

Parameter containing:
tensor([[ 0.4670, -0.5288],
        [ 0.5762,  0.4524],
        [ 0.5941, -0.5421]], requires_grad=True)

In [20]:
lineal_2.weight

Parameter containing:
tensor([[-0.3875,  0.2747, -0.5389]], requires_grad=True)

In [9]:
x = torch.arange(1,3)
x

tensor([1, 2])